#!/bin/bash
set -e

# ─── FastFoodie Server Setup Script ──────────────────────
# Download and run:
#   curl -fsSL https://raw.githubusercontent.com/popo1222/fastfoodie/main/setup.sh -o setup.sh
#   sudo bash setup.sh

INSTALL_DIR="/opt/fastfoodie"
REPO_BASE="https://raw.githubusercontent.com/popo1222/fastfoodie/main"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║         🍔 FastFoodie Server Setup           ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Check root ──────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root: sudo ./setup.sh"
  exit 1
fi

# ─── Collect info ────────────────────────────────────────
echo "We need a few details to configure your server."
echo ""

read -p "Admin panel domain (e.g. admin.myrestaurant.com): " ADMIN_DOMAIN
read -p "Customer app domain (e.g. order.myrestaurant.com): " WEBAPP_DOMAIN

if [ -z "$ADMIN_DOMAIN" ] || [ -z "$WEBAPP_DOMAIN" ]; then
  echo "❌ Both domains are required."
  exit 1
fi

# Generate JWT secret
JWT_SECRET=$(openssl rand -base64 48)
echo ""
echo "✅ Generated JWT secret automatically."

# ─── Install Docker ──────────────────────────────────────
echo ""
echo "📦 Installing Docker..."

if command -v docker &> /dev/null; then
  echo "  Docker already installed: $(docker --version)"
else
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  echo "  ✅ Docker installed: $(docker --version)"
fi

# ─── Install Caddy ───────────────────────────────────────
echo ""
echo "📦 Installing Caddy..."

if command -v caddy &> /dev/null; then
  echo "  Caddy already installed: $(caddy version)"
else
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
  echo "  ✅ Caddy installed: $(caddy version)"
fi

# ─── Create project directory ────────────────────────────
echo ""
echo "📁 Setting up ${INSTALL_DIR}..."

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download deployment files
curl -fsSL "${REPO_BASE}/docker-compose.yml" -o docker-compose.yml
curl -fsSL "${REPO_BASE}/update.sh" -o update.sh
curl -fsSL "${REPO_BASE}/watcher.sh" -o watcher.sh
chmod +x update.sh watcher.sh
mkdir -p triggers

# ─── Configure .env ──────────────────────────────────────
echo ""
echo "⚙️  Configuring environment..."

cat > .env <<EOF
# ─── FastFoodie Production Environment ────────────────────
# Generated by setup.sh on $(date)

DATABASE_URL="file:./dev.db"

JWT_SECRET="${JWT_SECRET}"
JWT_EXPIRES_IN="8h"

SESSION_EXPIRES_HOURS=4

HOST="0.0.0.0"
PORT=3000
NODE_ENV="production"

CORS_ORIGINS="https://${ADMIN_DOMAIN},https://${WEBAPP_DOMAIN}"

RATE_LIMIT_MAX=100
RATE_LIMIT_TIME_WINDOW="1 minute"

UPLOAD_DIR="./uploads"
MAX_FILE_SIZE=5242880
EOF

echo "  ✅ .env created"

# ─── Configure Caddy ────────────────────────────────────
echo ""
echo "🔒 Configuring Caddy (auto SSL)..."

cat > /etc/caddy/Caddyfile <<EOF
# FastFoodie — Auto-generated by setup.sh

${ADMIN_DOMAIN} {
    reverse_proxy localhost:8080
}

${WEBAPP_DOMAIN} {
    reverse_proxy localhost:8081
}
EOF

echo "  ✅ Caddyfile created for ${ADMIN_DOMAIN} + ${WEBAPP_DOMAIN}"

# ─── Setup Update Watcher (cron) ─────────────────────────
echo ""
echo "⏰ Setting up update watcher..."

# Remove old entries if re-running setup
crontab -l 2>/dev/null | grep -v "fastfoodie.*watcher" > /tmp/crontab.tmp || true

# Add watcher — runs every 30 seconds (two cron entries offset by 30s)
echo "* * * * * ${INSTALL_DIR}/watcher.sh" >> /tmp/crontab.tmp
echo "* * * * * sleep 30 && ${INSTALL_DIR}/watcher.sh" >> /tmp/crontab.tmp

crontab /tmp/crontab.tmp
rm /tmp/crontab.tmp
echo "  ✅ Update watcher installed (checks every 30s)"

# ─── Pull & Start ───────────────────────────────────────
echo ""
echo "🐳 Pulling Docker images..."
docker compose pull

echo ""
echo "🚀 Starting FastFoodie..."
docker compose up -d

# Wait for healthy
echo "  Waiting for API to be ready..."
sleep 15

# ─── Seed database ──────────────────────────────────────
echo ""
echo "🌱 Seeding database..."
docker compose exec -T api npx tsx prisma/seed.ts

# ─── Start Caddy ────────────────────────────────────────
echo ""
echo "🔒 Starting Caddy..."
systemctl restart caddy
systemctl enable caddy

# ─── Done ────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║           ✅ Setup Complete!                  ║"
echo "╠══════════════════════════════════════════════╣"
echo "║                                              ║"
echo "║  Admin:   https://${ADMIN_DOMAIN}            "
echo "║  Webapp:  https://${WEBAPP_DOMAIN}           "
echo "║                                              ║"
echo "║  Login:   admin@demo.com / admin123          ║"
echo "║  ⚠️  Change password after first login!      ║"
echo "║                                              ║"
echo "║  Files:   ${INSTALL_DIR}                     "
echo "║  Logs:    docker compose logs -f             ║"
echo "║  Update:  cd ${INSTALL_DIR} && ./update.sh   "
echo "║                                              ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Make sure DNS for ${ADMIN_DOMAIN} and ${WEBAPP_DOMAIN} points to this server"
echo "  2. Login to admin panel and change the default password"
echo "  3. Go to Settings → Set store name, logo, tables, and Webapp URL to https://${WEBAPP_DOMAIN}"
echo ""
